#!/usr/bin/with-contenv bash

# make folders (Original)
# mkdir -p \
	/config{/log/nginx,/log/rtorrent,/log/rutorrent,/nginx,/nginx/conf.d,/php,/rtorrent/rtorrent_sess,/rutorrent/settings/users} \
	/config/rutorrent/profiles{/settings,/torrents,/users,/tmp} \
	/downloads{/completed,/incoming,/watched} \
	/run{/nginx,/php} \
	/var/lib/nginx/tmp/client_body

# make folders
mkdir -p \
	/config{/log/nginx,/log/rtorrent,/nginx,/nginx/conf.d,/rtorrent/rtorrent_sess,/flood} \
	/run{/nginx} \
	/var/lib/nginx/tmp/client_body

# copy config
PREV_DIR=$(pwd)

cd "${PREV_DIR}" || exit

[[ ! -e /config/nginx/nginx.conf ]] && \
	cp /defaults/nginx.conf /config/nginx/nginx.conf

[[ ! -e /config/nginx/.htpasswd ]] && \
	cp /defaults/.htpasswd /config/nginx/.htpasswd
	
[[ ! -e /config/rtorrent/rtorrent.rc ]] && \
	cp /defaults/rtorrent.rc /config/rtorrent/rtorrent.rc

# delete lock file if exists
[[ -e /config/rtorrent/rtorrent_sess/rtorrent.lock ]] && \
	rm /config/rtorrent/rtorrent_sess/rtorrent.lock

# permissions
chown abc:abc /downloads

chown -R abc:abc \
	/config \
	/run \
	/var/lib/nginx

chmod 644 /etc/logrotate.d/*

if [ ! -e "/config/nginx/conf.d/basic.conf" ]
then
 cp /defaults/conf.d/* /config/nginx/conf.d/
fi

su -c "echo 'export PATH=$PATH:~/bin' >> ~/.profile" abc
