#!/usr/bin/with-contenv bash

# make folders
mkdir -p /config/tmp /detach_sess

# copy config files/set links etc...
[[ ! -f /config/flood/config.js ]] && cp /defaults/config.js /config/flood/config.js
[[ ! -L /usr/flood/config.js ]] && ln -s /config/flood/config.js /usr/flood/config.js && sed -i -e "s|<FLOOD_SECRET>|$FLOOD_SECRET|g" /config/flood/config.js && sed -i -e "s|<CONTEXT_PATH>|$CONTEXT_PATH|g" /config/flood/config.js

# set perms
chown abc:abc -R /config /detach_sess
chown abc:abc /downloads
chmod 755 /usr/local/bin/curl
